/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZV2ljKIAlj9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Archivo } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div
      className="grid grid-cols-1 gap-6 p-4 md:grid-cols-[1fr_300px] md:p-6 lg:grid-cols-[1fr_350px]">
      <div className="grid gap-6">
        <div>
          <h1 className="text-2xl font-bold">Titanium Alloy</h1>
          <p className="text-muted-foreground">A strong and lightweight metal</p>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Properties</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Property</TableHead>
                  <TableHead>Value</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>Density</TableCell>
                  <TableCell>4.5 g/cm³</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Melting Point</TableCell>
                  <TableCell>1,668°C</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Tensile Strength</TableCell>
                  <TableCell>900 MPa</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Hardness</TableCell>
                  <TableCell>36 HRC</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Thermal Conductivity</TableCell>
                  <TableCell>21.9 W/m·K</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Corrosion Resistance</TableCell>
                  <TableCell>Excellent</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Usage Examples</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="grid grid-cols-[80px_1fr] items-center gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Aerospace"
                  width={80}
                  height={80}
                  className="rounded-md"
                  style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                <div>
                  <h3 className="font-medium">Aerospace</h3>
                  <p className="text-muted-foreground">
                    Titanium alloys are widely used in aircraft and spacecraft due to their high strength-to-weight
                    ratio and corrosion resistance.
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-[80px_1fr] items-center gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Medical Implants"
                  width={80}
                  height={80}
                  className="rounded-md"
                  style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                <div>
                  <h3 className="font-medium">Medical Implants</h3>
                  <p className="text-muted-foreground">
                    Titanium alloys are biocompatible and are commonly used in medical implants such as hip and knee
                    replacements, dental implants, and pacemaker cases.
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-[80px_1fr] items-center gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Automotive"
                  width={80}
                  height={80}
                  className="rounded-md"
                  style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                <div>
                  <h3 className="font-medium">Automotive</h3>
                  <p className="text-muted-foreground">
                    Titanium alloys are used in high-performance automotive applications, such as engine components,
                    suspension parts, and exhaust systems, due to their strength and low weight.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Edit History</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead>Editor</TableHead>
                  <TableHead>Changes</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>2024-06-15</TableCell>
                  <TableCell>John Doe</TableCell>
                  <TableCell>Updated tensile strength and hardness values.</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>2024-05-20</TableCell>
                  <TableCell>Jane Smith</TableCell>
                  <TableCell>Added information about medical implant applications.</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>2024-04-01</TableCell>
                  <TableCell>Bob Johnson</TableCell>
                  <TableCell>Initial creation of the material page.</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
      <div className="grid gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Related Materials</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="grid grid-cols-[80px_1fr] items-center gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Stainless Steel"
                  width={80}
                  height={80}
                  className="rounded-md"
                  style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                <div>
                  <h3 className="font-medium">Stainless Steel</h3>
                  <p className="text-muted-foreground">
                    A corrosion-resistant alloy with a wide range of applications.
                  </p>
                  <Button size="sm" variant="outline">
                    View
                  </Button>
                </div>
              </div>
              <div className="grid grid-cols-[80px_1fr] items-center gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Aluminum Alloy"
                  width={80}
                  height={80}
                  className="rounded-md"
                  style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                <div>
                  <h3 className="font-medium">Aluminum Alloy</h3>
                  <p className="text-muted-foreground">
                    A lightweight and versatile metal with excellent corrosion resistance.
                  </p>
                  <Button size="sm" variant="outline">
                    View
                  </Button>
                </div>
              </div>
              <div className="grid grid-cols-[80px_1fr] items-center gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Carbon Fiber"
                  width={80}
                  height={80}
                  className="rounded-md"
                  style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                <div>
                  <h3 className="font-medium">Carbon Fiber</h3>
                  <p className="text-muted-foreground">
                    A strong and lightweight composite material with numerous applications.
                  </p>
                  <Button size="sm" variant="outline">
                    View
                  </Button>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Actions</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              <Button size="sm">Edit Material</Button>
              <Button size="sm" variant="secondary">
                Download Datasheet
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}
